version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydbForLibrary
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

    liquibase:
      image: liquibase:4.30.0
      depends_on:
        - postgres
      volumes:
        - ./test_project:/liquibase/changelog
      working_dir: /liquibase/changelog
      command:
        - --changeLogFile=db.changelog-master.xml
        - --url=jdbc:postgresql://postgres:5432/mydbForLibrary
        - --username=postgres
        - --password=postgres
        - update
