spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydbForLibrary
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
server:
  servlet:
    context-path: /library-app

